# fly.toml app configuration file generated for lnbits-telegram-bot on 2023-05-31T12:36:32-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lnbits-telegram-bot"
primary_region = "lax"
